CREATE TABLE LOG
(
   ID INTEGER NOT NULL,
   RAW VARCHAR(255) NOT NULL,
   REMOTE_HOST VARCHAR(255),
   RFC931 VARCHAR(255),
   AUTH_USER VARCHAR(255),
   ACCESS_DATE TIMESTAMP;
   METHOD VARCHAR(255),
   URI_PATH VARCHAR(255),
   PROTOCOL VARCHAR(255),
   STATUS INTEGER,
   BYTES INTEGER,
   PASSPORT_NUMBER VARCHAR(255),
   PRIMARY KEY(ID)
);

CREATE SEQUENCE LOG_SEQ_ID;
CREATE INDEX USER_IDX ON LOG(AUTH_USER);
CREATE INDEX STATUS_IDX ON LOG(STATUS);
CREATE INDEX METHOD_IDX ON LOG(METHOD);
COMMIT;